# Recitation 2
## LU Factorization

![](transform_diagram.png)

In the above diagram, a transformation was applied to the blue square which resulted in the red square. This is clearly a rotation, so we can write the this as a rotation matrix, where $(x,y)$ is a point on the blue square and $(x_t, y_t)$ is a point on the red square:

$$ \begin{bmatrix} a & c & 0 \\ c & d & 0 \\ 0 & 0 & 1 \end{bmatrix} 
\begin{bmatrix} x \\ y \\ 1 \end{bmatrix}
= \begin{bmatrix} x_t \\ y_t \\ 1 \end{bmatrix} \\\\
= \begin{bmatrix} a & b \\ c & d \end{bmatrix} 
\begin{bmatrix} x \\ y \end{bmatrix}
= \begin{bmatrix} x_t \\ y_t \end{bmatrix}
$$

Suppose we want to find the values $a$, $b$, $c$, and $d$ of this rotation matrix. First we will need to define two points from each square, then we can rearrange the equation into a different $Ax=b$ form so that $x$ contains $a$, $b$, $c$, and $d$. 

$$
(x_1, y_1) =  (2,2) \\
(x_2, y_2) =  (2, -2)\\
(x_{1t}, y_{1t}) = (0, 2\sqrt{2})\\
(x_{2t}, y_{2t}) =  (2\sqrt{2}, 0)\\
$$

$$
ax_1 + by_1 = x_{1t} \\
cx_1 + dy_1 = y_{1t} \\\\
ax_2 + by_2 = x_{2t} \\
cx_2 + dy_2 = y_{2t} \\
$$

$$
\begin{bmatrix} x_1 & y_1 & 0 & 0 \\ 0 & 0 & x_1 & y_1 \\ x_2 & y_2 & 0 & 0 \\ 0 & 0 & x_2 & y_2\end{bmatrix}
\begin{bmatrix} a \\ b \\ c \\ d\end{bmatrix}
= \begin{bmatrix} x_{1t} \\ y_{1t} \\ x_{2t} \\ y_{2t} \end{bmatrix}
$$

Plugging in the values, we finally get a system of equations that we can solve:

$$
\begin{bmatrix} 2 & 2 & 0 & 0 \\ 0 & 0 & 2 & 2 \\ 2 & -2 & 0 & 0 \\ 0 & 0 & 2 & -2\end{bmatrix}
\begin{bmatrix} a \\ b \\ c \\ d\end{bmatrix}
= \begin{bmatrix} 0 \\ 2\sqrt(2) \\ 2\sqrt(2) \\ 0 \end{bmatrix}
$$

To solve, we will use LU factorization on the A matrix. since $A_{1,1} = 0$, we will have to use permutations.

<img src="LU_with_permutations.png" width="700">

Implement the algorithm above, taken from 5.6 in the course booklet, to perform LU factorization on matrix $A$.

In [7]:
using LinearAlgebra

# declare A
A = [2 2 0 0; 0 0 2 2; 2 -2 0 0; 0 0 2 -2];
b = [0; 2sqrt(2); 2sqrt(2);0]
# initialization
n, m = size(A)
temp = copy(A)
L = Array{Float64, 2}(undef, n, 0)
U = Array{Float64, 2}(undef, 0, n)
eps = 1e-16
Kappa = 10

# P starts as the identity matrix
P = [1 0 0 0;
     0 1 0 0; 
     0 0 1 0; 
     0 0 0 1]

for k = 1:n
    # Your code here
end

@show L
@show U
@show P

L = Matrix{Float64}(undef, 4, 0)
U = Matrix{Float64}(undef, 0, 4)
P = [1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1]


4×4 Matrix{Int64}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1

Now you can use Julia's builtin `lu()` function to check your answer:

In [8]:
@show A
F2 = lu(A)
L2 = F2.L
U2 = F2.U
P2 = F2.P

display(L2)
display(U2)
display(P2)

4×4 Matrix{Float64}:
 1.0   0.0  0.0  0.0
 1.0   1.0  0.0  0.0
 0.0  -0.0  1.0  0.0
 0.0  -0.0  1.0  1.0

4×4 Matrix{Float64}:
 2.0   2.0  0.0   0.0
 0.0  -4.0  0.0   0.0
 0.0   0.0  2.0   2.0
 0.0   0.0  0.0  -4.0

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0

A = [2 2 0 0; 0 0 2 2; 2 -2 0 0; 0 0 2 -2]


In [21]:
# Forward substitution, for L, Pb
n = 4
y = zeros(n)


@show y

y = [0.0, 2.8284271247461903, 2.8284271247461903, -2.8284271247461903]


4-element Vector{Float64}:
  0.0
  2.8284271247461903
  2.8284271247461903
 -2.8284271247461903

In [28]:
# Backward Substitution, for U, y
n = 4
x = zeros(n)



@show x

4-element Vector{Float64}:
  0.7071067811865476
 -0.7071067811865476
  0.7071067811865476
  0.7071067811865476

# Lets check what we have!

In [29]:
T = [x[1] x[2]; x[3] x[4]]

2×2 Matrix{Float64}:
 0.707107  -0.707107
 0.707107   0.707107

In [30]:
T*[2;2]

2-element Vector{Float64}:
 0.0
 2.8284271247461903