# Control Flow in Julia

Now that we are comfortable using Julia for declaring and manipulating variabels and Arrays, the next logical step is to learn to control the flow of these manipulations. 

Control Statements used in Julia are:

- for loops
- while loops
- if-else construct
- do while


# For Loops

Used when we want to repeat a process, or a segment of code.  

The basic syntax is illustrated in the next cell.


In [1]:
# Use the keyword 'for' followed by the condition

# i is called an iterator, that keeps track of the number of times the code has run

#v For this problem we are simply printing the value of the iterator 

for i = 1:10
    @show i
end


i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9
i = 10


In [2]:
# combine two loops 

for i = 1:4
    for j = 2:4
        @show i*j
    end
end

i * j = 2
i * j = 3
i * j = 4
i * j = 4
i * j = 6
i * j = 8
i * j = 6
i * j = 9
i * j = 12
i * j = 8
i * j = 12
i * j = 16


In [3]:
for i = 1:4,j = 2:4
    @show i*j
end

i * j = 2
i * j = 3
i * j = 4
i * j = 4
i * j = 6
i * j = 8
i * j = 6
i * j = 9
i * j = 12
i * j = 8
i * j = 12
i * j = 16


# Different ways to specify a range

The iterator in the loop is specified as a range of valid numbers. There are different ways of building ranges in julia. 


In [5]:
for i = 1:3:10
    @show i
end

i = 1
i = 4
i = 7
i = 10


In [13]:
? LinRange

search: LinRange



```
LinRange{T}
```

A range with `len` linearly spaced elements between its `start` and `stop`. The size of the spacing is controlled by `len`, which must be an `Int`.

# Examples

```jldoctest
julia> LinRange(1.5, 5.5, 9)
9-element LinRange{Float64}:
 1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5
```

Compared to using [`range`](@ref), directly constructing a `LinRange` should have less overhead but won't try to correct for floating point errors:

```julia
julia> collect(range(-0.1, 0.3, length=5))
5-element Array{Float64,1}:
 -0.1
  0.0
  0.1
  0.2
  0.3

julia> collect(LinRange(-0.1, 0.3, 5))
5-element Array{Float64,1}:
 -0.1
 -1.3877787807814457e-17
  0.09999999999999999
  0.19999999999999998
  0.3
```


In [7]:
a = UnitRange(1,10)

1:10

In [9]:
@show a.start
@show a.stop;

a.start = 1
a.stop = 10


In [10]:
a1 = 1:10

1:10

In [11]:
a == a1

true

In [12]:
@show typeof(a)
@show typeof(a1);

typeof(a) = UnitRange{Int64}
typeof(a1) = UnitRange{Int64}


In [14]:
b = LinRange(1,10,6)

6-element LinRange{Float64}:
 1.0,2.8,4.6,6.4,8.2,10.0

In [15]:
@show b.start
@show b.stop
@show b.len;

b.start = 1.0
b.stop = 10.0
b.len = 6


# Loops in arrays 

We've accessed Arrays using slices, which we now can call ranges. 

In [16]:
MyArray = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15]

1×15 Array{Int64,2}:
 1  2  3  4  5  6  7  8  9  10  11  12  13  14  15

In [17]:
MyArray[1:10]

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [18]:
MyArray[a]

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [19]:
# Ranges are also arrays
a[4]

4

In [20]:
collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [22]:
comp = [sin(i) for i in 1:5]

5-element Array{Float64,1}:
  0.8414709848078965
  0.9092974268256817
  0.1411200080598672
 -0.7568024953079282
 -0.9589242746631385

# If-Else Condition 

When you want to run a part of your code based on a condition

In [23]:
if (a[4] == 4)
    @show a;
end

a = 1:10


1:10

In [27]:
x = 10;
y = 4;
if(!(x<y))
    println("x is less than y");
else
    println("x is greater than or equal to y")
end

x is less than y


In [26]:
x<y

false

# Logical Operator

When you want to specify condition, you have to work with Logical variables, Boolean (true and false)

Special oprators that can manipulate them are called Logical Operators

The most commonly used logical operators are Not ```!```, And ```&&```, Or ```||```



Not operator is unary logical operator, i.e. it only applies to a single variable. 
It function is negate a logical expression. So true becomes false and false becomes true. 

In [28]:
@show !true
@show !false
@show !(2==2);

!true = false
!false = true
!(2 == 2) = false


The And && operator is used in expression when we need two or more evaluating conditions to be met (or be true) simultanously. Any condition that is not met is a deal-breaker and the expression evaluates to false.

In [29]:
@show true&&false
@show false&&true
@show true&&true
@show false&&false;

true && false = false
false && true = false
true && true = true
false && false = false


We can have multiple expressions in this format

In [30]:
@show true&&true&&false
@show true&&true&&true
@show (2==2)&&(1<=1)
@show (2>=2.0)&&(-1.0<0)&&(-1.0<-1)
@show (2<=0)&&true;


true && (true && false) = false
true && (true && true) = true
2 == 2 && 1 <= 1 = true
2 >= 2.0 && (-1.0 < 0 && -1.0 < -1) = false
2 <= 0 && true = false


Finally, The Or || operator is used in cases when even one satifactory condition is accceptable. If we want either of the conditions specified to be true, we use Or to evaluate the final expression to a true

In [31]:
@show true||false
@show false||true
@show true||true
@show false||false;

true || false = true
false || true = true
true || true = true
false || false = false


We could chain multiple expressions this way. We would get a true value if either or the expression evaluates to true. Let's see! 

In [32]:
@show (2==2)||(1<0)||(-1<0)
@show (2.0<3) || false;

2 == 2 || (1 < 0 || -1 < 0) = true
2.0 < 3 || false = true


# Most common way of combining the two flows!

# Break in a loop

Using the keyword ```break``` will stop the loop at the whatever statement it is encountered. 

An opposite of that is continue, but we will not discuss that one today. 

In [2]:
# You want special action, on some values in a loop

# Program to check if 19 is prime 

number = 25;

for i = 2:number-1
    if(number%i == 0)
        display("Not a prime number");
        break;
    end  
    # Was not in the recording, but I did say we were missing another if! SO I put that here!
    if(i==number-1)
    display("Prime Number")
    end
end
        

# code here

"Not a prime number"

# Matrix Multiplication  using loops

$A=\left[\begin{array}{rrr}  2 & -4 & 2  \\
 3 & 4 & 8  \end{array}\right] B =  \left[\begin{array}{rr} 2 & -5 \\
6 & -3  \\ 3 & 2\end{array}\right] $

In [35]:
A = [2 -4 2;3 4 8];
B = [2 -5;6 -3;3 2];

In [37]:
# Standard multiplication

# Iterate over all the indices of C

C = Array{Float64,2}(undef, 2, 2);

for i = 1:2, j=1:2
    C[i,j] = A[i,:]'*B[:,j];
end
C

2×2 Array{Float64,2}:
 -14.0    6.0
  54.0  -11.0

In [42]:
# Column wise multiplication

# Run the loop k times

C = zeros(2,2);

for i = 1:size(A,2)
    C = C + A[:,i]*B[i,:]';
end

C# code here

2×2 Array{Float64,2}:
 -14.0    6.0
  54.0  -11.0

# Solving system of equations using LU decomposition 


In [43]:
M = [1 2 1;1 -3 4;3 1 -2];
temp=copy(M)
n,m = size(M)
k=1
L = Array{Float64,2}(undef, n, 0);
U = Array{Float64,2}(undef, 0,n);
C=temp[:,k]
pivot=C[k]
C=C/pivot  
R=temp[k,:]' 
L = [L C]
U = [U;R]
temp = temp-C*R
display(temp)
display(L)
display(U);

3×3 Array{Float64,2}:
 0.0   0.0   0.0
 0.0  -5.0   3.0
 0.0  -5.0  -5.0

3×1 Array{Float64,2}:
 1.0
 1.0
 3.0

1×3 Array{Float64,2}:
 1.0  2.0  1.0

In [44]:
k=2
C=temp[:,k]
pivot=C[k]
C=C/pivot  
R=temp[k,:]' 
temp = temp-C*R
L = [L C]
U = [U;R]
display(temp)
display(L)
display(U);

3×3 Array{Float64,2}:
 0.0  0.0   0.0
 0.0  0.0   0.0
 0.0  0.0  -8.0

3×2 Array{Float64,2}:
 1.0  -0.0
 1.0   1.0
 3.0   1.0

2×3 Array{Float64,2}:
 1.0   2.0  1.0
 0.0  -5.0  3.0

In [45]:
k=3
C=temp[:,k]
pivot=C[k]
C=C/pivot  
R=temp[k,:]' 
L = [L C]
U = [U;R]
temp = temp-C*R
display(temp)
display(L)
display(U);

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

3×3 Array{Float64,2}:
 1.0  -0.0  -0.0
 1.0   1.0  -0.0
 3.0   1.0   1.0

3×3 Array{Float64,2}:
 1.0   2.0   1.0
 0.0  -5.0   3.0
 0.0   0.0  -8.0

In [46]:
M == L*U

true

# Looping to find LU Decomposition

In [47]:
M = [1 2 1;1 -3 4;3 1 -2];
n,m = size(M)
temp = copy(M)
L = Array{Float64,2}(undef, n, 0)  
U = Array{Float64,2}(undef, 0, n)  

# code here

for k = 1:n
    C=temp[:,k]
    pivot=C[k]
    C=C/pivot  
    R=temp[k,:]' 
    L = [L C]
    U = [U;R]
    temp = temp-C*R
end

display("final answer is:")
display(temp)
display(L)
display(U)

"final answer is:"

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

3×3 Array{Float64,2}:
 1.0  -0.0  -0.0
 1.0   1.0  -0.0
 3.0   1.0   1.0

3×3 Array{Float64,2}:
 1.0   2.0   1.0
 0.0  -5.0   3.0
 0.0   0.0  -8.0

In [48]:
M == L*U

true